### Get access token from OIDC server
POST {{oauthUrl}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type = password &
client_id = {{clientId}} &
username = {{clientUsername}} &
password = {{clientSecret}}
> {%
    client.global.set("access_token", response.body.access_token)
%}

### Add event
POST http://127.0.0.1:5000/events
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "AggregateId": "<AggregateId>",
  "Type": "<create>",
  "Data": "<string_data>"
}

### Get all records for AggregateId
GET 127.0.0.1:5000/events/<AggregateId>
Accept: application/json
Authorization: Bearer {{access_token}}

### Get record for AggregateId and Timestamp
GET 127.0.0.1:5000/events/<AggregateId>/<Timestamp>
Accept: application/json

###
