### GET request to example server
POST http://127.0.0.1:5000/events
Content-Type: application/json
Accept: application/json

{
  "aggregate_id": "aggregate_1",
  "event": "create",
  "data": "string_data"
}

###
GET 127.0.0.1:5000/events/aggregate_1
Accept: application/json

###
GET 127.0.0.1:5000/events/aggregate_1/<_replace_>
Accept: application/json

###
